# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4e5bc007d9077f67a47f067aa273ab707efa6d8c68ccd157984489a2b3d5450747dd1d413cfb8faee8b30cafbedd04b3de3f0e85344d12966dd741b9c2c9464

test:
  secret_key_base: 88c9d2df9bde9eb5fc3710b700e6c924bf437c04f454cff9252fd87e1a2fc1340b69249f81c760e54690a7c6b93bdf06eae7423ef19b26821d8dc9764cff20ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
